name: ${project.name}
version: ${project.version}
author: totemo
authors: [totemo]
description: ${project.description}
website: ${project.url}
main: nu.nerd.swav.ShroomWithAView

depend: [WorldGuard]
softdepend: [LogBlock]

permissions:
  shroomwithaview.admin:
    description: Permission to administer the plugin.
    default: op

commands:
  shroomwithaview:
    description: ${project.name} administrative command.
    permission: shroomwithaview.admin
    usage: |
      /<command> reload: Reload the configuration.
